import {
  type LucideIcon,
  List,
  MapPin,
  MapPinOff,
  MapPinned,
  Route,
  Clock,
  Wallet,
  Plus,
  PlusCircle,
  ImagePlus,
  ImageOff,
  ArrowLeft,
  ArrowRight,
  ArrowDown,
  ArrowUpRight,
  ArrowUpLeft,
  ClipboardList,
  Wrench,
  Calendar,
  Camera,
  Car,
  CarTaxiFront,
  CreditCard,
  MessageCircle,
  Check,
  CheckCircle2,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  X,
  Palette,
  Trash2,
  FileText,
  FolderOpen,
  Download,
  Pencil,
  AlertCircle,
  AlertTriangle,
  Eye,
  HelpCircle,
  History,
  Home,
  IdCard,
  Inbox,
  Info,
  Share2,
  Lightbulb,
  Fuel,
  Tag,
  Truck,
  Lock,
  LogOut,
  Mail,
  Menu,
  Banknote,
  LocateFixed,
  Navigation,
  BellRing,
  ExternalLink,
  SlidersHorizontal,
  User,
  CircleUser,
  Phone,
  ShieldAlert,
  ShieldCheck,
  Shield,
  QrCode,
  ScanLine,
  CircleDot,
  ReceiptText,
  RefreshCw,
  Rocket,
  Search,
  Settings,
  Star,
  Headset,
  HeartHandshake,
  Heart,
  HeartPulse,
  KeyRound,
  Key,
  Briefcase,
  Sparkles,
  Package,
  Boxes,
  Box,
  Shirt,
  Book,
  Smartphone,
  Tv,
  Dog,
  PawPrint,
  Gem,
  Watch,
  HardHat,
  Zap,
  Armchair,
  Bed,
  Refrigerator,
  Bike,
  Music,
  Megaphone,
  ShoppingBag,
  ShoppingCart,
  ShoppingBasket,
  Pill,
  Gift,
  Flower2,
  UtensilsCrossed,
  Salad,
  Wine,
  Store,
  TicketPercent,
  LifeBuoy,
  UserPlus,
  UserCheck,
  Map,
  Crown,
  Landmark,
  Triangle,
  Bus,
  Building2,
  Power,
  Navigation2,
  Contact,
  BadgeCheck,
  Cross,
  Flame,
  Bell,
  ShieldUser,
  XCircle,
  DollarSign,
} from "lucide-react-native";

/**
 * Lucide é a ÚNICA fonte de ícones do app.
 *
 * Este resolver converte nomes de ícone vindos de dados dinâmicos
 * (configs de marcadores, listas de itens, propósitos vindos do backend etc.)
 * no componente Lucide correspondente. Aceita tanto nomes no estilo Lucide
 * (ex.: "ShoppingBag") quanto nomes legados estilo Material/Ionicons
 * (ex.: "shopping-bag", "map-marker") para facilitar a migração.
 */
const LUCIDE_ICONS: Record<string, LucideIcon> = {
  // ── Nomes estilo Lucide (categorias / propósitos) ──
  UtensilsCrossed,
  FastForward: UtensilsCrossed,
  Salad,
  Wine,
  FileText,
  FolderOpen,
  ShoppingBag,
  ShoppingCart,
  ShoppingBasket,
  Pill,
  HeartPulse,
  Gift,
  Flower2,
  Package,
  Boxes,
  Key,
  Shirt,
  Book,
  Smartphone,
  Tv,
  Sparkles,
  Dog,
  Heart,
  PawPrint,
  Gem,
  Watch,
  Mail,
  Wrench,
  Tool: Wrench,
  HardHat,
  Briefcase,
  Zap,
  Rocket,
  Home,
  Armchair,
  Bed,
  Refrigerator,
  Bike,
  Music,
  Megaphone,
  Box,
  List,
  MapPin,
  Car,

  // ── Nomes legados estilo Material / Ionicons / FontAwesome ──
  "access-time": Clock,
  "account-balance-wallet": Wallet,
  add: Plus,
  "add-circle": PlusCircle,
  "add-photo-alternate": ImagePlus,
  "arrow-back": ArrowLeft,
  "arrow-downward": ArrowDown,
  "arrow-forward": ArrowRight,
  "arrow-left": ArrowLeft,
  "assignment-ind": ClipboardList,
  "build-outline": Wrench,
  "calendar-outline": Calendar,
  "call-made": ArrowUpRight,
  camera: Camera,
  car: Car,
  "car-outline": Car,
  "card-outline": CreditCard,
  "credit-card": CreditCard,
  "cc-amex": CreditCard,
  "cc-mastercard": CreditCard,
  "cc-visa": CreditCard,
  "chat-bubble-outline": MessageCircle,
  check: Check,
  "check-circle": CheckCircle2,
  checkmark: Check,
  "chevron-right": ChevronRight,
  "chevron-forward": ChevronRight,
  "chevron-back": ChevronLeft,
  "expand-less": ChevronUp,
  "expand-more": ChevronDown,
  close: X,
  "color-palette-outline": Palette,
  "delete-forever": Trash2,
  "document-text-outline": FileText,
  download: Download,
  edit: Pencil,
  "edit-location-alt": MapPinned,
  error: AlertCircle,
  "error-outline": AlertCircle,
  eye: Eye,
  help: HelpCircle,
  history: History,
  home: Home,
  "id-card": IdCard,
  "image-not-supported": ImageOff,
  inbox: Inbox,
  info: Info,
  "info-outline": Info,
  "information-circle-outline": Info,
  "ios-share": Share2,
  lightbulb: Lightbulb,
  "local-gas-station": Fuel,
  "local-offer": Tag,
  "local-shipping": Truck,
  "local-taxi": CarTaxiFront,
  "location-off": MapPinOff,
  "location-on": MapPin,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  "mail-outline": Mail,
  "map-marker": MapPin,
  "map-marker-distance": Route,
  menu: Menu,
  money: Banknote,
  "money-bill-wave": Banknote,
  "my-location": LocateFixed,
  "near-me": Navigation,
  "north-west": ArrowUpLeft,
  "notifications-active": BellRing,
  "open-in-new": ExternalLink,
  "options-outline": SlidersHorizontal,
  person: User,
  "person-circle-outline": CircleUser,
  phone: Phone,
  "privacy-tip": ShieldAlert,
  "qr-code": QrCode,
  "qrcode-scan": ScanLine,
  "radio-button-checked": CircleDot,
  "receipt-long": ReceiptText,
  refresh: RefreshCw,
  "rocket-launch": Rocket,
  schedule: Clock,
  search: Search,
  settings: Settings,
  shield: Shield,
  star: Star,
  "support-agent": Headset,
  "task-alt": CheckCircle2,
  "time-outline": Clock,
  tune: SlidersHorizontal,
  "verified-user": ShieldCheck,
  "volunteer-activism": HeartHandshake,
  "vpn-key": KeyRound,
  "wallet-outline": Wallet,
  warning: AlertTriangle,
  cancel: XCircle,
  "star-border": Star,
  "power-settings-new": Power,
  notifications: Bell,
  "two-wheeler": Bike,
  "directions-car": Car,
  city: Building2,
  motorcycle: Bike,
  motorbike: Bike,
  scooter: Bike,
  truck: Truck,
  van: Truck,
  "airport-shuttle": Bus,
  store: Store,
  restaurant: UtensilsCrossed,
  "cube-outline": Package,
  "package-variant-closed": Package,
  package: Package,
  place: MapPin,
  work: Briefcase,
  favorite: Heart,
  email: Mail,
  chat: MessageCircle,
  payment: CreditCard,
  "local-police": Shield,
  "local-hospital": Cross,
  "fire-truck": Flame,
  "share-location": MapPinned,
  contacts: Contact,
  verified: BadgeCheck,
  "attach-money": DollarSign,
  security: ShieldCheck,
  description: FileText,
  // Drawer / navegação (MaterialCommunityIcons)
  "map-marker-path": Route,
  "store-clock-outline": Store,
  "receipt-text-outline": ReceiptText,
  wallet: Wallet,
  "credit-card-outline": CreditCard,
  "ticket-percent-outline": TicketPercent,
  "account-circle": CircleUser,
  account: User,
  bell: Bell,
  "shield-check": ShieldCheck,
  lifebuoy: LifeBuoy,
  "shield-account-outline": ShieldUser,
  "account-multiple-plus-outline": UserPlus,
  cog: Settings,
  map: Map,
  cash: Banknote,
  "star-circle": Star,
  "car-info": Car,
  "file-document-outline": FileText,
  "help-circle": HelpCircle,
  crown: Crown,
  bank: Landmark,
  // Status / formas geométricas
  "circle-outline": CircleDot,
  circle: CircleDot,
  "circle-ring": CircleDot,
  diamond: Gem,
  triangle: Triangle,
  // Nomes estilo Lucide usados em metadados de status
  "user-check": UserCheck,
  navigation: Navigation,
  "navigation-2": Navigation2,
  "map-pin": MapPin,
  "x-circle": XCircle,
  "check-circle-lucide": CheckCircle2,
};

/** Resolve um nome de ícone (Lucide ou legado) para o componente Lucide. */
export function getLucideIcon(name?: string | null): LucideIcon {
  if (!name) return List;
  return LUCIDE_ICONS[name] || List;
}

/** @deprecated Use getLucideIcon. Mantido para compatibilidade. */
export const mapIconName = getLucideIcon;
